version: '3'
services:
  node_app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=kravi43500
      - MONGO_PASSWORD=password%40
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=kravi43500
      - MONGO_INITDB_ROOT_PASSWORD=password@
  
  